"""initial schema

Revision ID: 2c4bfa7498a7
Revises: 
Create Date: 2026-09-14 07:03:51.699112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c4bfa7498a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=False),
    sa.Column('phase', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('problem_or_risk_event', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('impact', sa.String(length=255), nullable=True),
    sa.Column('trigger_indicator', sa.Text(), nullable=True),
    sa.Column('strategy', sa.Enum('REDUCE', 'TRANSFER', 'AVOID', 'ACCEPT', name='action_strategy'), nullable=True),
    sa.Column('lesson_learned', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('hashtags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('source_risk_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_risk_id'], ['risks.id'], name='fk_lessons_source_risk_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spp_code', sa.String(length=7), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('curator', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spp_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('RISK_MANAGER', 'RISK_OWNER', 'INITIATOR', 'ADMIN', name='project_role_name'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('display_number', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('TECHNOLOGICAL', 'TECHNICAL', 'PROCESS', 'REGULATORY', 'DESIGN', 'CONSTRUCTION', 'PROCUREMENT', 'ECONOMIC', name='risk_category'), nullable=False),
    sa.Column('status', sa.Enum('IDENTIFICATION', 'ANALYSIS_ASSESSMENT', 'MANAGEMENT', 'MONITORING_CONTROL', 'CLOSED', 'ARCHIVED_MERGED', name='risk_status'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('owner_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('identification_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('identification_phase', sa.String(length=255), nullable=True),
    sa.Column('realization_phase', sa.String(length=255), nullable=True),
    sa.Column('cause', sa.Text(), nullable=False),
    sa.Column('risk_event', sa.Text(), nullable=False),
    sa.Column('direct_consequence', sa.Text(), nullable=False),
    sa.Column('p_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('p', sa.Integer(), nullable=True),
    sa.Column('i_level', sa.Integer(), nullable=True),
    sa.Column('i_justification', sa.Text(), nullable=True),
    sa.Column('rra', sa.Integer(), nullable=True),
    sa.Column('quant_probability_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quant_schedule_impact_months', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('quant_budget_impact_mln', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('scenarios', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_loss', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('committee_flag', sa.Boolean(), nullable=False),
    sa.Column('committee_decision', sa.Text(), nullable=True),
    sa.Column('committee_decision_date', sa.Date(), nullable=True),
    sa.Column('residual_rra', sa.Integer(), nullable=True),
    sa.Column('residual_expected_loss', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('source_lesson_id', sa.String(length=16), nullable=True),
    sa.Column('review_frequency_days', sa.Integer(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('merged_into_risk_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merged_into_risk_id'], ['risks.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('CAUSE', 'CONSEQUENCE', 'CONTINGENCY', 'EXISTING_PROCEDURE', name='action_kind'), nullable=False),
    sa.Column('strategy', sa.Enum('REDUCE', 'TRANSFER', 'AVOID', 'ACCEPT', name='action_strategy'), nullable=False),
    sa.Column('trigger_condition', sa.Text(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('cost', sa.String(length=100), nullable=True),
    sa.Column('planned_date', sa.String(length=50), nullable=True),
    sa.Column('forecast_actual_date', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'DONE', 'REJECTED', name='action_status'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('IDENTIFICATION', 'ANALYSIS_ASSESSMENT', 'MANAGEMENT', 'MONITORING_CONTROL', 'CLOSED', 'ARCHIVED_MERGED', name='risk_status'), nullable=True),
    sa.Column('to_status', sa.Enum('IDENTIFICATION', 'ANALYSIS_ASSESSMENT', 'MANAGEMENT', 'MONITORING_CONTROL', 'CLOSED', 'ARCHIVED_MERGED', name='risk_status'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_risk_id', sa.String(length=32), nullable=False),
    sa.Column('to_risk_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('REINFORCES', 'LEADS_TO', 'DEPENDS_ON', 'DUPLICATES', name='risk_dependency_type'), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'AI_SUGGESTED', name='risk_dependency_source'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_risk_id'], ['risks.id'], ),
    sa.ForeignKeyConstraint(['to_risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_dependencies')
    op.drop_table('audit_logs')
    op.drop_table('actions')
    op.drop_table('risks')
    op.drop_table('project_roles')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('lessons')
    # ### end Alembic commands ###

    # Не сгенерировано автоматически: Postgres ENUM — именованные типы уровня БД,
    # переживающие DROP TABLE. Без явного удаления повторный downgrade->upgrade
    # падает с "type already exists" (проверено вручную при валидации миграции).
    bind = op.get_bind()
    for enum_name in (
        "action_kind",
        "action_strategy",
        "action_status",
        "project_role_name",
        "risk_category",
        "risk_status",
        "risk_dependency_type",
        "risk_dependency_source",
    ):
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
